### ISSUE TITLE
coredhcp.io/plugins goes 404

### ISSUE THREAD

**Issue by th3goose** [coredhcp/coredhcp#130] opened 2021-04-28 21:06 UTC
The links to plugins on coredhcp.io go to 404 currently.

**Comment by insomniacslk** [comment] 2021-04-28 21:17
Duplicate of #128, working on a fix

**Closed** 2021-04-28 21:17 UTC
Labels: duplicate

**Comment by th3goose** [comment] 2021-04-28 21:53
Oh gotcha sorry didn't dig close enough at 128

**Comment by insomniacslk** [comment] 2021-04-28 22:14
No worries!
